---
- hosts: all
  become: true
  vars:
   download_url: https://git.kernel.org/torvalds/t/linux-5.1-rc4.tar.gz
  tasks:
  - name: Download Linux Kernel
    command: "wget --no-check-certificate --no-cookies {{download_url}} "
  - name: Unpack the loved Linux Kernel
    command: "tar xvzf linux-5.0.7.tar.xz"
